# Example configuration file for ReactBench with new calculators
# This file demonstrates how to use the new calculator modules

# ReactBench installation path (optional, defaults to "/root/ReactBench")
# This path will be set as REACTBENCH_PATH environment variable
reactbench_path: /root/ReactBench

# input parameters for running reaction conformational sampling
inp_path:      data  # a folder of target reaction xyz files
scratch:       test-4   # output and working folder of RCS 
nprocs:        28     # total number of cpus for performing YARP

# input parameters for calculation
charge:        0     # system charge
multiplicity:  1     # system multiplicity (spin + 1)

# Available calculator options:
# - leftnet: LeftNet model with autograd (fine-tuned)
# - leftnet-d: LeftNet model with direct forces (fine-tuned)
calc:          mace-pretrain   # select from the available MLFF calculators, like: 

# input parameters for GSM
gsm_restart:   True          # restart GSM jobs or not
num_nodes:     9             # number of nodes in GSM string
max_gsm_iters: 50            # maximum number of total iterations
max_opt_steps: 5             # maximum optimization steps in each iteration
add_node_tol:  0.1           # tol for adding a new node
conv_tol:      0.0005        # tol for gradrms
fixed_R:       False         # fix reactant geometry
fixed_P:       False         # fix product geometry
dmax:          0.1           # DMAX parameter in GSM
gsm_wt:        3600          # walltime for a gsm job (in s)

# input parameters for PYSIS
select:        tight         # this will affect the selection rule of low-level calculations results
pysis_restart: True          # restart PYSIS jobs or not
python_exe:    python        # python path for calling GSM calculations
pysis_exe:     pysis         # pysis path

# Device configuration (optional, defaults to "cpu")
device:        cpu           # device to run calculations on ("cpu" or "cuda") 